- hosts: splunk
  become: yes
  tasks:
    - name: Check Splunk Forwarder status
      command: /opt/splunkforwarder/bin/splunk status
      register: splunk_status

    - debug:
        var: splunk_status.stdout
